apiVersion: v1
kind: Service
metadata:
  name: smb-webapp
  labels:
    app: smb-webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: smb-webapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-webapp
  labels:
    app: smb-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-webapp
  template:
    metadata:
      labels:
        app: smb-webapp
    spec:
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-demo
      containers:
      - name: demo-webapp
        image: nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: smb
          mountPath: "/usr/share/nginx/html/"
          readOnly: false
